[build]
  functions = "functions"
  command = "npm install"  # Asegúrate de ajustar esto según las necesidades de tu proyecto
  publish = "public"  # Ajusta si el directorio de tus archivos estáticos es diferente

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"


