[[build]]
  comand= "npm install"
  publish= 'public'

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/"
  to = "/dist/index.html"
  status = 200